[workspace]
authors = ["zsk4 <zachary_katz@mines.edu>"]
channels = ["conda-forge"]
name = "infinite_access"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
icepyx = ">=2.0.0,<3"
sliderule = ">=4.18.1,<5"
earthaccess = ">=0.14.0,<0.15"
ipykernel = ">=6.30.1,<7"
